version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
    create_infrastructure:
        # The primary container, where your job's commands will run
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout # check out the code in the project directory
          - run:
              name: Create Stack with Cloudformation
              command: |
                aws cloudformation deploy \
                  --template-file template.yml \
                  --stack-name demo-stack-${CIRCLE_WORKFLOW_ID:0:5} \
                  --region us-east-1

    configure_infrastructure: 
        docker:
          - image: python:3.7-alpine3.11
        steps:
          - checkout
          - add_ssh_keys:
                fingerprints: ["9a:4f:91:43:23:dd:28:e5:55:a1:4b:ae:fa:c1:db:92"] 
          - run:
              name: Install Ansible
              command: |
                apk add --update ansible
          - run:
              name: Run Playbook and Configure server
              command: |
                ansible-playbook -i inventory main.yml

# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure